service: openai-student-proxy

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    SECRET_KEY: ${env:SECRET_KEY, 'dev-secret-key'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
